FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy EVERYTHING first (removes path issues completely)
COPY . .

# Restore
RUN dotnet restore Gender.Api.csproj

# Publish
RUN dotnet publish Gender.Api.csproj -c Release -o /app/publish

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Gender.Api.dll"]